name: Build & Deploy Prospector

on:
  push:
    branches: [main]

env:
  IMAGE_REPO: ghcr.io/seedpod-mailer/prospector
  NAMESPACE: mailer-infra

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1 — pull code so Docker build context exists
      - uses: actions/checkout@v4

      # 2 — authenticate to GHCR
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PAT }}

      # 3 — build & push the image for this commit
      - uses: docker/build-push-action@v5
        with:
          context: ./agents/prospector
          push: true
          tags: ${{ env.IMAGE_REPO }}:sha-${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # 1 — check out repo again so Helm sees ./helm/prospector
      - uses: actions/checkout@v4

      # 2 — write kubeconfig from secret
      - name: Decode kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > kubeconfig
          echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV

      # 3 — install Helm CLI
      - uses: azure/setup-helm@v3
        with:
          version: v3.12.0   # any recent 3.x is fine

      # 4 — helm upgrade / install
      - name: Helm upgrade
        run: |
          helm upgrade --install prospector ./helm/prospector \
            --namespace $NAMESPACE --create-namespace \
            --set image.repository=$IMAGE_REPO \
            --set image.tag=sha-${{ github.sha }}

